### ISSUE TITLE
Config to specify table, column options

### ISSUE THREAD

**Issue by enkeboll** [memsql/dbt-singlestore#5]
Similar to how it works in the [Redshift connector](https://github.com/dbt-labs/dbt-redshift/blob/c7d7495a2023a66457a61d69b24ad2e921f842d7/dbt/adapters/redshift/impl.py#L18-L22), I'd expect there to be configurable table or column options:
- sort key / clustered columnstore key
- primary key
- unique
- index
- shard key
- encoding and collation

Much of the functionality of these Redshift analogs is written in the [`include/redshift/macros/adapters.sql`](https://github.com/dbt-labs/dbt-redshift/blob/4b81b0be700e926faba4963388d00c232d6493fe/dbt/include/redshift/macros/adapters.sql) file, which doesn't seem to exist for Singlestore.

**Comment by kannan-aravind-1** [comment]
Hi, thanks for opening the issue. I think a model level config called storage_type (rowstore or columnstore) would be useful in this. Below is a quick shim I did for this in my project. 

`
{% macro singlestore__create_table_as(temporary, relation, sql) -%}
    {%- set sql_header = config.get('sql_header', none) -%}
	{%- set storage_type = config.get('storage_type', 'columnstore') -%}
    {{ sql_header if sql_header is not none }}
    create {% if storage_type == 'rowstore': -%} rowstore {%- endif %} {% if temporary: -%} temporary{%- endif %} table
        {{ relation.include(database=True) }}
    as
        {{ sql }}
{% endmacro %}
`
