### ISSUE TITLE
dbt 1.1.0 claims incompatibility with dbt-singlestore

### ISSUE THREAD

**Issue by andyenkeboll-iex** [memsql/dbt-singlestore#8]
https://github.com/memsql/dbt-singlestore/blob/45f12e2b96237d40317022b2427e2cd7f252b847/setup.py#L21
dbt-singlestore defines valid dbt-core versions as >1.0.0, but I see the following error after upgrading to dbt 1.1.0

<img width="552" alt="image" src="https://user-images.githubusercontent.com/69856377/169946488-6c963d01-c4fb-4eb5-a543-f9df1f4889ed.png">

**Comment by pmishchenko-ua** [comment]
Thanks for reporting this @andyenkeboll-iex ! Apparently `dbt --version` checks that the version of the plugin is the same as the version of the core (except for the patch part). Therefore this message is expected, though it is kind of misleading - I've just run the tests to check that 1.0.0 version of the singlestore adapter works fine with dbt-core 1.1.0. Anyway, we are going to make a new release in the next two weeks, and we'll update the version accordingly.
